apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sa-logic
spec:
  replicas: 1
  minReadySeconds: 15
  template:
    metadata:
      labels:
        app: sa-logic
    spec:
      containers:
        - image: wangjunjie/sentiment-analysis-logic
          imagePullPolicy: IfNotPresent
          name: sa-logic
          ports:
            - containerPort: 5000
