apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sa-web-app
spec:
  replicas: 1
  minReadySeconds: 15
  template:
    metadata:
      labels:
        app: sa-web-app
    spec:
      containers:
      - image: wangjunjie/sentiment-analysis-web-app
        imagePullPolicy: IfNotPresent
        name: sa-web-app
        env:
          - name: SA_LOGIC_API_URL
            value: "http://sa-logic"
        ports:
          - containerPort: 8080
